services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: devnology-ecommerce-challenge-app
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
  db:
    build: .docker/postgres
    container_name: devnology-ecommerce-challenge-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - TZ=${TZ}
      - PGTZ=${PGTZ}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
